export const contactTranslations = {
   en: {
      name: 'Name *',
      email: 'Email *',
      subject: 'Subject *',
      message: 'Message *',
      send: 'Send Message',
      contact: 'CONTACT INFO',
      mail: 'MAIL ADDRESSES',
      number: 'CONTACT NUMBER',
      location: 'CURRENT LOCATION',
      street: '#30 Villa carolina 2da',
      city: 'Hato Nuevo',
      state: 'Santo Domingo',
      country: 'Dominican Republic',
      social: 'SOCIAL MEDIA',
   },
   es: {
      name: 'Nombre *',
      email: 'Correo *',
      subject: 'Asunto *',
      message: 'Mensaje *',
      send: 'Enviar Mensaje',
      contact: 'INFORMACIÓN DE CONTACTO',
      mail: 'DIRECCIONES DE CORREO',
      number: 'NUMERO DE CONTACTO',
      location: 'UBICACIÓN ACTUAL',
      street: '#30 Villa carolina 2da',
      city: 'Hato Nuevo',
      state: 'Santo Domingo',
      country: 'Republica Dominicana',
      social: 'REDES SOCIALES',
   },
}; 
