export const skillsTranslations = {
   en: {
      title: 'SKILLS & EXPERTISE',
      subtitle: 'Technical skills and proficiency levels',
      stats: 'Statistics',
      highlights: 'Key Highlights',
      categories: 'Skill Categories',
      level: 'Level',
      beginner: 'Beginner',
      intermediate: 'Intermediate',
      advanced: 'Advanced',
      expert: 'Expert',
      totalSkills: 'Total Skills',
      expertLevel: 'Expert Level',
      totalProjects: 'Total Projects',
      yearsExperience: 'Years Experience',
      frontendTechnologies: 'Frontend Technologies',
      mostDiverseCategory: 'Most diverse category',
      advancedSkills: 'Advanced+ Skills',
      productionReady: 'Production ready',
      mostUsedCategory: 'Most Used Category',
      byProjectCount: 'By project count',
   },
   es: {
      title: 'HABILIDADES Y EXPERTISE',
      subtitle: 'Habilidades técnicas y niveles de competencia',
      stats: 'Estadísticas',
      highlights: 'Puntos Clave',
      categories: 'Categorías de Habilidades',
      level: 'Nivel',
      beginner: 'Principiante',
      intermediate: 'Intermedio',
      advanced: 'Avanzado',
      expert: 'Experto',
      totalSkills: 'Total de Habilidades',
      expertLevel: 'Nivel Experto',
      totalProjects: 'Total de Proyectos',
      yearsExperience: 'Años de Experiencia',
      frontendTechnologies: 'Tecnologías Frontend',
      mostDiverseCategory: 'Categoría más diversa',
      advancedSkills: 'Habilidades Avanzadas+',
      productionReady: 'Listo para producción',
      mostUsedCategory: 'Categoría Más Usada',
      byProjectCount: 'Por cantidad de proyectos',
   },
};
